name: Java CI with Maven

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven (skip tests)
      run: mvn -B clean compile -DskipTests --file pom.xml

    - name: Build JAR
      run: mvn -B package -DskipTests --file pom.xml

    - name: Verify JAR file
      run: |
        ls -la target/
        file target/*.jar
        jar tf target/*.jar | head -10

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HyperBounty-java-${{ matrix.java-version }}
        path: target/*.jar
        retention-days: 7
