name: Java CI with Maven

on:
  push:
    branches: [ "main", "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Verify build
      run: |
        ls -la target/
        echo "✅ Build completed successfully!"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HyperBounty
        path: target/*.jar
